spring:
  application:
    name: crm-rest-cf
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: "jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DBNAME}"
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  liquibase:
    contexts: prod